interiorem/elliptics

example/eblob_backend.cpp, tests/new_api_test.cpp
- `test_update_bigger_json` - call update_json with json bigger than reserved capacity
and check that update_json is failed with -E2BIG
- `test_update_json_noexist` - call update_json for nonexistent key
and check that update_json is failed with -ENOENT
- `test_update_json_uncommitted` - prepare record by a key,
call update_json for this uncommitted key and
check that update_json is failed with -ENOENT
=> Fix update_json and add tests for its bad cases

example/eblob_backend.cpp, tests/new_api_test.cpp
plain_write and commit will return:
* `-ENOENT` for nonexistent records
* `-EPERM` for committed records
=> Fix returning wrong error status by plain_write and commit

bindings/python/elliptics_session.cpp, tests/pytests/test_newapi.py
**MERGE AFTER #32***
Add test for calling different methods of cloned `newapi.Session`
=> python: Fix cloning newapi.Session 

bindings/cpp/newapi/session.cpp
Keep serializaed packet in `read_handler::inner_handler` to guarantee that `dnet_trans_control` contains valid data.
=> Fix using data after free

bindings/python/dnet_client
This option enables filtering iterated keys by `user_flags` and
specifies `user_flags` that should be grabbed.
=> Add multi option '--user-flags' to dnet_client iterate

tests/pytests/test_recovery.py
Recovery tests in their cleanups did not wait route-list updates which led to using incomplete route-list by others and incorrect cleanup in teardown.
=> pytests: fix failing monitor tests

bindings/python/dnet_client, bindings/python/elliptics_session.cpp, bindings/python/result_entry.cpp
- `lookup` - lookup key in specified groups
- `read` - read key's json and/or data from specified groups
- `write` - write key with json and/or data in specified groups
- `remove` - remove key from specified groups
- `update_json` - update key's json in specified groups
=> dnet_client: add new subcommands 

library/dnet.c, library/elliptics.h, library/node.c, tests/server_send.cpp
Conflicts:
tests/server_send.cpp
=> server-send: check that moving keys to itself doesn't permitted

debian/control, srw/srw.cpp, tests/srw_test_app.cpp
=> refact(cocaine): adapt to 0.12.10

recovery/elliptics_recovery/dc_recovery.py, recovery/elliptics_recovery/dc_server_send.py, recovery/elliptics_recovery/types/dc.py, tests/pytests/test_recovery.py
=> Recovery remove new

debian/control, srw/srw.cpp, tests/cocaine.conf
Cosmetic updates to cocaine core interface change.
The easiest (and hopefully the last) srw update.
=> Update srw to cocaine 0.12.11

monitor/http_miscs.hpp, monitor/server.cpp, monitor/server.hpp
Final log is printed for all successful requests and contains several timings.
=> monitor: refactor http server and add final log

monitor/procfs_provider.cpp
If speed can't be get, it will be shown as `-1`.
=> stats: add interfaces' speed to procfs/net

bindings/cpp/logger.cpp, debian/control
Depends on https://github.com/3Hren/blackhole/pull/173
=> create logger with asynchronous sink by make_file_logger

tests/pytests/test_recovery.py
test for https://github.com/interiorem/elliptics/pull/171
=>  tests: add test_dc_with_insufficient_route_list

bindings/cpp/session.cpp, bindings/python/dnet_client, bindings/python/elliptics_python.cpp, bindings/python/elliptics_session.cpp, bindings/python/python.hpp, bindings/python/result_entry.cpp, bindings/python/src/__init__.py, bindings/python/src/newapi.py, bindings/python/src/session.py, debian/control, elliptics-bf.spec, example/eblob_backend.c, example/ioclient.cpp, include/elliptics/interface.h, include/elliptics/packet.h, include/elliptics/session.hpp, library/backend.cpp, library/backend.h, library/dnet_common.c, tests/backends_test.cpp
- add support of eblob's background inspect
- allow to set ioprio to backend via config
=> Eblob's background inspect & ioprio

bindings/cpp/functional_p.h, bindings/cpp/logger.cpp, bindings/cpp/newapi/session.cpp, bindings/cpp/session.cpp, bindings/python/elliptics_python.cpp, bindings/python/src/log.py, example/eblob_backend.c, example/ioserv.json, example/iterate_move.cpp, include/elliptics/logger.hpp, include/elliptics/newapi/result_entry.hpp, library/backend.cpp, library/elliptics.h, library/logger.hpp, library/net.c, library/pool.c, library/trans.c, tests/new_api_test.cpp, tests/test_base.cpp
Add "access" log level with minimal verbosity and useful information
=> Add access logs

bindings/cpp/newapi/session.cpp, recovery/elliptics_recovery/monitor.py, recovery/elliptics_recovery/recovery.py
This guarantees that monitor will be correctly shutdown and its statistics will be correctly written.
=>  recovery: use monitor with `with` statement

recovery/elliptics_recovery/dc_server_send.py, tests/pytests/test_recovery.py
Only failures about data corruption will be count as data error, so data on groups answered with such error will be overwrote.
=>  recovery: do not consider all server-send failures as data error

bindings/cpp/newapi/session.cpp, bindings/python/elliptics_session.cpp, example/eblob_backend.cpp, include/elliptics/core.h, include/elliptics/newapi/session.hpp, library/protocol.cpp, library/protocol.hpp, recovery/elliptics_recovery/dc_server_send.py, tests/new_api_server_send_test.cpp
=> Add chunk_retry_count to server-send and use it in recovery

example/eblob_backend.cpp, tests/new_api_test.cpp
=> Clear each `bulk_read*` iteration status

example/eblob_backend.cpp, tests/corrupted_stamp_test.cpp
=> Check for corrupted stamp on session::read_json.

library/elliptics.h, library/net.c, library/net.cpp, library/node.c, library/trans.c, tests/forwarding_test.cpp
Rework of the branch https://github.com/shaitan/elliptics/tree/debug
=> Fix timeouts gain on DC became inaccessible

library/server.c
I've tested all cases of deinit, by replacing:
```
err = dnet_xxx_init(...);
if (err)
goto err_xxx;
```
on
```
//err = dnet_xxx_init(...);
err = -123;
if (err)
goto err_xxx;
```
No hang-up, no core (at `ulimit -c unlimited`).
=> fix: initialize monitor after other server_node's inner components

debian/control, example/eblob_backend.c, example/eblob_backend.cpp, tests/pytests/test_defrag.py
Connected with https://github.com/interiorem/eblob/pull/40
This PR adds ability to set single_pass_file_size_threshold in eblob via elliptics.
=> feat: proxy single_pass_threshold to eblob
