interiorem/elliptics

library/trans.c

"backend: %" was moved into `dnet_print_trans`.

logs: fix mistake in format string

---

recovery/elliptics_recovery/dc_recovery.py
recovery/elliptics_recovery/dc_server_send.py
recovery/elliptics_recovery/iterator.py
recovery/elliptics_recovery/recovery.py
recovery/elliptics_recovery/types/dc.py
tests/pytests/test_recovery.py

recovery: added --user_flags option: recover key if at least one replica has user_flags from specified user_flags_set
If user_flags from all key's replicas are not in user_flags_set, then this key will be skipped during recovery. If user_flags_set is not specified (by default), then recovery will not skip any keys.

Recovery mask

---

library/backend.cpp

It hangs on cache deinitialization because cache's lifecheck thread doesn't stop.
Lifecheck thread stops when either node's `need_exit` or backend's `need_exit` is set.

Fix hanging backend intialization

---

example/eblob_backend.cpp

Disable exceptions for session used by server-send

Fix crashing node on failed write during server-send

---

debian/control
srw/srw.cpp
tests/cocaine.conf
tests/srw_test.cpp
tests/srw_test_app.cpp

Before this change srw was sending sph to the cocaine worker explicitly, as a prefix to the actual user payload, so cocaine worker was required to manually separate its input into sph and payload.
Not only it meant an extra work for authors of cocaine apps, but also it made apps dependent on the execution context: same app could not run without a change under both standalone cociane runtime or srw. (While it was possible to guess about presence of the sph prefix, it couldn't be done reliably).
Here comes handy the new feature of cocaine-v12 -- headers. And ability to use them to pass supplemental data separate but along with user data.
This change passes sph through cocaine invocation headers. So workers for srw (which have no use for sph) can be exactly the same as for standalone …

Hide sph in cocaine invocation headers

---

debian/changelog
srw/CMakeLists.txt
tests/CMakeLists.txt

Cocaine now provides common functionality in separate library. Elliptics SRW library and tests should link with it

srw: link with new cocaine-io-util shared lib

---

.gitmodules
CMakeLists.txt
debian/control
include/elliptics/logger.hpp

In preparation to coming migration to blackhole v1.0.
Elliptics packages now will not have dependency on blackhole v0.2.
Clients using elliptics client will be required to add blackhole as submodule
in their own source tree by themselves.

Move blackhole v0.2 to submodule

---

bindings/python/result_entry.cpp
tests/pytests/test_newapi.py

Return `None` in:
* `newapi.LookupResultEntry.path`
* `newapi.LookupResultEntry.record_info`
* `newapi.ReadResultEntry.record_info`
* `newapi.ReadResultEntry.io_info`
* `newapi.ReadResultEntry.json`
* `newapi.ReadResultEntry.data`
for an entry with error in status.
Add tests for it.

python: return None in read/lookup result entry's property on error

---

include/elliptics/async_result.hpp
library/dnet.c
tests/new_api_test.cpp

Added test which turns backend into RO and checks that write into this backend is failed with -EROFS error.

Check RO status of backend on WRITE_NEW

---

bindings/python/elliptics_session.cpp
tests/pytests/test_newapi.py

Updated behaviour of `newapi.Session.timestamp` and `newapi.Session.json_timestamp`: now if they aren't specified or are reset they will be None.

Add json_timestamp to elliptics.newapi.Session

---

cache/cache.cpp
debian/control
example/config.cpp
example/config.hpp
example/config_impl.cpp
library/CMakeLists.txt
library/backend.cpp
library/backend.h
monitor/backends_stat_provider.cpp
monitor/monitor.cpp
monitor/monitor.hpp
tests/CMakeLists.txt
tests/backends_test.cpp

Use libkora-util instead of `dynamic_t` from `blackhole` and internal implementation of `config_t` and `config_parser_t`.
Store and provide via monitor all json objects used in each backend initialization.

Use libkora-util

---

tests/pytests/conftest.py
tests/pytests/test_monitor_top.py
tests/pytests/test_newapi.py
tests/pytests/test_recovery.py
tests/pytests/test_session_indexes.py
tests/pytests/test_session_iterator.py
tests/pytests/test_session_monitor_and_statistics.py
tests/pytests/test_session_parameters.py
tests/pytests/test_session_rwr.py
tests/pytests/test_session_srw.py

Fixture `server` was renameved to `servers`. Where fixture `servers` is implicitly used it is replaces by using decorator `@pytest.mark.usefixtures("servers")`.

pytests: fix srw tests which occasionally fails

---

debian/control

Build with libcocaine-dev=0.12.8.11+nmu1 and libcocaine-core3=0.12.8.11+nmu1 fails on:
```
/usr/bin/ld: cannot find -lcocaine-io-util
collect2: error: ld returned 1 exit status
```

depends: update depends on libcocaine-dev and libcocaine-core3 to '>=0.12.8.15'

---

cocaine/include/cocaine/api/elliptics_node.hpp
debian/control
srw/localnode.cpp
srw/localnode.hpp
srw/srw.cpp
tests/cocaine.conf

Adapt to new possibility of cocaine to register new components.
This is required for upcoming storage accessor service, also localnode initialization is now made via config as a common service. Bound to https://github.com/3Hren/cocaine-core/pull/97

Cocaine component registration

---

bindings/python/async_result.cpp
bindings/python/async_result.h

Some operations on iterator cause waiting for new responses and without releasing GIL it sometimes leads to deadlock.

python: wrap python_async_result::iterator to free GIL in long operations

---

library/pool.c

If there are a lot of small responses which should be sent to some state with good connection, e.g. iterator generates such responses, net thread can get into cycle of sending these responses and will not send responses to other states until cycle is done. If responses is rather small, the cycle will be done only when all responses are sent.
I've added break to this cycle if a response is fully sent, so net thread will switch to another state for sending response to it.

net: fix addicting net thread on sending responses to one state

---

cache/cache.cpp
cache/slru_cache.cpp
example/eblob_backend.c
example/eblob_backend.cpp
example/eblob_backend.h
include/elliptics/interface.h
library/dnet.c
library/elliptics.h
monitor/top.cpp

Add `dnet_cmd_stats` which will be pass to all handlers to collect statistics about command handling like: time spent by the command in queue, wheather the command was handled by cache, time spent on command handling and size of command's data (for read - size of read data, for write - size of written data, for others - 0).
Add sending to commands and top statistics info about handling READ_NEW and WRITE_NEW.

stats: update commands and top statistics for {READ,WRITE}_NEW

---

bindings/cpp/newapi/session.cpp
bindings/cpp/session.cpp
bindings/python/elliptics_session.cpp
bindings/python/src/newapi.py
bindings/python/src/session.py
include/elliptics/interface.h
include/elliptics/packet.h
include/elliptics/session.hpp
library/dnet_common.c
library/elliptics.h
library/net.c
library/net.cpp
library/node.c
library/protocol.cpp
library/protocol.hpp
library/trans.c
tests/CMakeLists.txt
tests/forwarding_test.cpp

All read, write, lookup and remove requests will be sent to the forward node which
in turn resend them to proper node if they are connected.

forward: add ability to set forward node in session

---

cocaine/include/cocaine/idl/localnode.hpp
srw/localnode.cpp
srw/localnode.hpp
tests/srw_test.cpp

localnode is of the same logical level as elliptics session, they are equally low-level. Only the user of localnode (and/or session) could know the required execution mode of the commands and specifics of the required I/O, hence only the user could specify proper set of command and/or I/O flags.
Session class have `set_{c,io}flags` methods for that -- so localnode methods must accept `{c,io}flags` parameters.
Note flags whitelisting -- we don't want to give the user an unbounded freedom here (some of the {c,io}flags are really for elliptics internal use only, some are dangerous, and some just don't have sense or meaning in the context of localnode).

localnode: methods accept flags

---

srw/CMakeLists.txt
srw/localnode.cpp
srw/srw.cpp
tests/CMakeLists.txt
tests/srw_test.cpp
tests/srw_test_app.cpp
tests/test_base.cpp

Adds tracing support at all places where request execution goes from elliptics to cocaine or from cocaine to elliptics.
There are still problems but we consider them temporary:
1) trace_id conversion from hex string to int64 in logger_adapter
2) not an optimal behavior due to differences in tracing logic between elliptics and cocaine (cocaine considers presence of trace as elliptics considers presence of trace+tracebit)
First should be alleviated by making cocaine switch to keep trace_id log attribute as integer (should happen soon).

Localnode and srw tracing

---

bindings/cpp/logger.cpp
bindings/cpp/session.cpp
debian/control
example/ioserv.json
library/backend.h
srw/srw.cpp
tests/test_base.cpp

Get rid of using hard-coded default trace_id and specify local timezone in timestamp specification

update to blackhole v1.2.1

---

recovery/elliptics_recovery/types/dc.py

Do not wait completion of all iterations to fail recovery.

recovery: fail immediately when some iteration is failed

---

recovery/elliptics_recovery/dc_server_send.py
recovery/elliptics_recovery/recovery.py
recovery/elliptics_recovery/types/merge.py

Corrupted keys are dumped one per line and in follow format: `{key} {group} [address/backend]`.

recovery: dump corrupted keys into {tmp_dir}/corrupted_keys file

---

library/net.c
library/pool.c

Now net thread will print start/finish sent log on notice, intermediate sent log on debug and only final finish sent on info.
Also it will decrease level of log that is printed when a net thread switches from state because it has reached `send_limit`.

logs: decreas number of logs printed on info level

---

recovery/elliptics_recovery/types/dc.py
recovery/elliptics_recovery/utils/misc.py

1. Get rid of extra temporary list creation in dump_key()
2. Removed is_chunked check (it must have been done in https://github.com/interiorem/elliptics/pull/68)
3. Optimized dump_key_data() that is called very often in inner cycles

recovery: optimizations

---

example/config.cpp
example/config.hpp
library/backend.cpp
library/backend.h
library/elliptics.h
library/pool.c
library/request_queue.cpp
library/request_queue.h
monitor/backends_stat_provider.cpp
tests/queue_timeout.cpp

Now backends can have different queue_timeout.

Allow to override global queue timeout for a backend.

---

bindings/python/src/misc.py

elliptics.Node.add_remotes converts different types of remotes by itself, so elliptics.create_node shouldn't do it.

python: pass remotes as is in elliptics.create_node

---

library/pool.c

Stalled net_state is checked via sending `DNET_CMD_BACKEND_STATUS` and is reset by its handler in case of timeout.

Do not reset stalled net_state in dnet_io_process_network

---

library/net.c
library/pool.c

Now it will be decremented after a connection lost

fix 'io.output.queue.size' statistic

---

library/backend.cpp

For `DNET_CMD_BACKEND_CONTROL` packet reply with `-ENOENT` if specified backend is not found.
Previously it was `-EINVAL` and cause confusion with other errors.

Return -ENOENT if a backend is not found

---

bindings/cpp/timer.hpp
cache/cache.cpp
cache/cache.hpp
cache/local_session.h
cache/slru_cache.cpp

Remove elliptics_timer and use steady_timer instead.
lock(): separate time spent on locking the mutex and time spent in unlocked state, since the last is not so critical.

elliptics_unique_lock refactoring and improvements

---

recovery/elliptics_recovery/dc_recovery.py
recovery/elliptics_recovery/dc_server_send.py
recovery/elliptics_recovery/recovery.py
recovery/elliptics_recovery/types/dc.py
tests/pytests/test_recovery.py

`--ro-groups` specifies readonly groups where no writes or removes will be sent.

 recovery: add --ro-groups

---

library/request_queue.cpp
tests/queue_timeout.cpp

Inform client about dropped request

---

example/eblob_backend.cpp
example/eblob_backend.h
tests/CMakeLists.txt
tests/corrupted_stamp_test.cpp

Check corrupted signature in user data, return _-EILSEQ_, if found. 
**TODO**:

Check for corrupted signature in user data

---

library/backend.cpp

Previously, backends were enabled in blocking system io pool that fills its queue and prevents other requests to be handled. This change switch enabling to nonblocking system io pool.

backends: enable backend in nonblocking sys io pool

---

bindings/cpp/session.cpp
library/backend.cpp

Also revert "backends: enable backend in nonblocking sys io pool", because it affects other commands handling while backends are started

 backends: handle backends_status request in nonblocking sys pool

---

recovery/elliptics_recovery/dc_recovery.py
recovery/elliptics_recovery/monitor.py
recovery/elliptics_recovery/utils/misc.py

* fix misusage of RecoverStat that leads to exception and hanging recovery
* fix typo that doesn't raise prepared exception
* use graceful shutdown for monitor via post message, so all updates will we applied before shutdown

recovery: fixes

---

recovery/elliptics_recovery/dc_server_send.py
recovery/elliptics_recovery/types/dc.py
recovery/elliptics_recovery/utils/misc.py
tests/pytests/test_mocked_recovery.py

It is possible that all keys from the bucket are already recovered (from previous buckets), so it is empty, but other buckets could still have keys to recover and we shouldn't stop here.
TODO:

recovery: fix stopping on empty bucket for server-send

---

example/config.cpp
example/config.hpp
library/backend.cpp
library/elliptics.h
library/pool.c
library/request_queue.cpp
library/request_queue.h

Introduce new io_pool mode: DNET_WORK_IO_MODE_LIFO In this mode io_pool will use LIFO instead of FIFO order for internal queue.

LIFO for nonblocking requests queueing

---

example/config.cpp

Additional case when lifo should be true by default.

fix: use lifo by default in all cases

---

cache/cache.cpp
cache/cache.hpp
cache/slru_cache.cpp
cache/slru_cache.hpp
example/eblob_backend.c
example/eblob_backend.cpp
include/elliptics/interface.h
library/backend.cpp
library/backend.h
library/common.cpp
library/common.hpp
library/dnet.c
library/elliptics.h
library/n2_protocol.cpp
library/n2_protocol.h
library/n2_protocol.hpp
library/net.c
library/net.cpp
library/protocol.cpp
library/protocol.hpp
library/protocol_common.hpp

I suggest to review at first these files in this order:
* `library/elliptics.h` (changes in `dnet_io_req`)
* `library/n2_protocol.hpp` (details, what we place in `dnet_io_req`)
* `include/elliptics/interface.h` (see `dnet_backend_callbacks::n2_command_handler`)
These changes are basic. If you don't agree with any, let's discuss till result convention.

Support protocol-independent cache read and write

---

example/config.cpp
example/config.hpp

Now fields from `config.options.io_pools.defaults` will be used as default values for all backends' io pools. If `config.options.io_pools.defaults` is missed or has missed some fields, these values will be taken from config for sys io pool.

pools: allow to specify default config for backends' io pools
